<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CamposSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('campos')->insert([
            [
                'id' => 1,
                'nome' => 'Menu Principal',
                'idCampo' => 'menu',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 25,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => 1,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 1,
                'ordem' => 0,
                'conteudo' => '',
                'created_at' => '2012-05-29 07:52:42',
                'updated_at' => '2012-05-29 07:52:42'
            ],
            [
                'id' => 2,
                'nome' => 'Slide',
                'idCampo' => 'slide',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 26,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => 1,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => 1,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 2,
                'ordem' => 1,
                'conteudo' => '',
                'created_at' => '2012-03-01 12:06:25',
                'updated_at' => '2012-03-01 12:06:25'
            ],
            [
                'id' => 3,
                'nome' => 'Destaque Lateral',
                'idCampo' => 'destaqueLateral',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => null,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 3,
                'ordem' => 2,
                'conteudo' => '<ul>
<li class="first"><a href="#"><img width="260" height="180" src="/media/images/vegetables.jpg" /></a><p>Lorem ipsum dolor sit</p></li>
<li><a href="#"><img width="260" height="180" src="/media/images/pastries.jpg" /></a><p>Mirum est notare quam</p></li>
</ul>',
                'created_at' => '2012-05-29 09:48:14',
                'updated_at' => '2012-05-29 09:48:14'
            ],
            [
                'id' => 4,
                'nome' => 'Campo modelo para apresentação',
                'idCampo' => 'destaqueMaior',
                'situacaoTitulo' => true,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => 1,
                'noticias' => null,
                'noticiasLimit' => 5,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => 1,
                'categoriasLimit' => 10,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => 1,
                'membros' => 5,
                'membrosLimit' => 3,
                'secao' => 3,
                'ordem' => 3,
                'conteudo' => '<p>Empalhamento Carlos dolor sit amet...</p>',
                'created_at' => '2012-05-29 08:22:42',
                'updated_at' => '2012-05-29 08:22:42'
            ],
            [
                'id' => 5,
                'nome' => 'Destaque rodape 1',
                'idCampo' => 'destaqueRodape',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => null,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 4,
                'ordem' => 5,
                'conteudo' => '<p><a href="index.html"><img width="286" height="238" src="/media/images/baking-fruits.png" /></a></p>',
                'created_at' => '2012-05-29 09:42:38',
                'updated_at' => '2012-05-29 09:42:38'
            ],
            [
                'id' => 6,
                'nome' => 'Destaque rodape 2',
                'idCampo' => 'destaqueRodape',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => null,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 4,
                'ordem' => 6,
                'conteudo' => '<p><a href="index.html"><img width="320" height="240" src="/media/images/health-benefits.png" /></a></p>',
                'created_at' => '2012-05-29 09:35:07',
                'updated_at' => '2012-05-29 09:35:07'
            ],
            [
                'id' => 7,
                'nome' => 'Destaque rodape 3',
                'idCampo' => 'destaqueRodape',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => null,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 4,
                'ordem' => 4,
                'conteudo' => '<p><a href="index.html"><img width="307" height="240" src="/media/images/vitamins.png" /></a></p>',
                'created_at' => '2012-05-29 08:29:30',
                'updated_at' => '2012-05-29 08:29:30'
            ],
            [
                'id' => 8,
                'nome' => 'copyrights',
                'idCampo' => 'footnote',
                'situacaoTitulo' => false,
                'situacao' => true,
                'restricao' => 1,
                'restricaoEspecifica' => '',
                'tipo' => 1,
                'pagina' => null,
                'noticias' => null,
                'noticiasLimit' => null,
                'artigos' => null,
                'artigosLimit' => null,
                'produtos' => null,
                'produtosLimit' => null,
                'pacotes' => null,
                'pacotesLimit' => null,
                'slides' => null,
                'slidesLimit' => null,
                'download' => null,
                'categorias' => null,
                'categoriasLimit' => null,
                'galeria' => null,
                'galeriaLimit' => null,
                'menus' => null,
                'membros' => null,
                'membrosLimit' => null,
                'secao' => 4,
                'ordem' => 7,
                'conteudo' => '<p>© 2011 Healthy Life. All Rights Reserved.</p>',
                'created_at' => '2012-04-26 07:45:06',
                'updated_at' => '2012-04-26 07:45:06'
            ]
        ]);
    }
}