<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagensSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('imagens')->insert([
            [
                'id' => 24,
                'arquivo' => '/media/images/galerias/slide-24.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 0,
                'created_at' => '2011-08-29 11:31:51',
                'updated_at' => '2011-08-29 11:31:51'
            ],
            [
                'id' => 25,
                'arquivo' => '/media/images/galerias/slide-25.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 1,
                'created_at' => '2011-08-29 11:31:51',
                'updated_at' => '2011-08-29 11:31:51'
            ],
            [
                'id' => 27,
                'arquivo' => '/media/images/galerias/slide-27.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2011-08-29 11:31:52',
                'updated_at' => '2011-08-29 11:31:52'
            ],
            [
                'id' => 28,
                'arquivo' => '/media/images/galerias/slide-28.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 3,
                'created_at' => '2011-08-29 11:31:53',
                'updated_at' => '2011-08-29 11:31:53'
            ],
            [
                'id' => 29,
                'arquivo' => '/media/images/galerias/slide-29.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 4,
                'created_at' => '2011-08-29 11:31:53',
                'updated_at' => '2011-08-29 11:31:53'
            ],
            [
                'id' => 30,
                'arquivo' => '/media/images/galerias/slide-30.jpg',
                'legenda' => 'Imagem de Galeria de exemplo de cartão de visitas',
                'slides' => null,
                'galerias' => 2,
                'produtos' => null,
                'link' => null,
                'ordem' => 5,
                'created_at' => '2011-08-29 11:31:55',
                'updated_at' => '2011-08-29 11:31:55'
            ],
            [
                'id' => 31,
                'arquivo' => '/media/images/galerias/slide-31.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 3,
                'created_at' => '2011-08-29 11:32:12',
                'updated_at' => '2011-08-29 11:32:12'
            ],
            [
                'id' => 33,
                'arquivo' => '/media/images/galerias/slide-33.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 0,
                'created_at' => '2011-08-29 11:32:13',
                'updated_at' => '2011-08-29 11:32:13'
            ],
            [
                'id' => 34,
                'arquivo' => '/media/images/galerias/slide-34.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 7,
                'created_at' => '2011-08-29 11:32:14',
                'updated_at' => '2011-08-29 11:32:14'
            ],
            [
                'id' => 35,
                'arquivo' => '/media/images/galerias/slide-35.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 7,
                'created_at' => '2011-08-29 11:32:14',
                'updated_at' => '2011-08-29 11:32:14'
            ],
            [
                'id' => 36,
                'arquivo' => '/media/images/galerias/slide-36.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 6,
                'created_at' => '2011-08-29 11:32:15',
                'updated_at' => '2011-08-29 11:32:15'
            ],
            [
                'id' => 37,
                'arquivo' => '/media/images/galerias/slide-37.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 8,
                'created_at' => '2011-08-29 11:32:15',
                'updated_at' => '2011-08-29 11:32:15'
            ],
            [
                'id' => 38,
                'arquivo' => '/media/images/galerias/slide-38.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 9,
                'created_at' => '2011-08-29 11:32:16',
                'updated_at' => '2011-08-29 11:32:16'
            ],
            [
                'id' => 39,
                'arquivo' => '/media/images/galerias/slide-39.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 10,
                'created_at' => '2011-08-29 11:32:16',
                'updated_at' => '2011-08-29 11:32:16'
            ],
            [
                'id' => 40,
                'arquivo' => '/media/images/galerias/slide-40.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 11,
                'created_at' => '2011-08-29 11:32:17',
                'updated_at' => '2011-08-29 11:32:17'
            ],
            [
                'id' => 41,
                'arquivo' => '/media/images/galerias/slide-41.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 12,
                'created_at' => '2011-08-29 11:32:17',
                'updated_at' => '2011-08-29 11:32:17'
            ],
            [
                'id' => 42,
                'arquivo' => '/media/images/galerias/slide-42.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 13,
                'created_at' => '2011-08-29 11:32:18',
                'updated_at' => '2011-08-29 11:32:18'
            ],
            [
                'id' => 43,
                'arquivo' => '/media/images/galerias/slide-43.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 14,
                'created_at' => '2011-08-29 11:32:18',
                'updated_at' => '2011-08-29 11:32:18'
            ],
            [
                'id' => 44,
                'arquivo' => '/media/images/galerias/slide-44.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 15,
                'created_at' => '2011-08-29 11:32:19',
                'updated_at' => '2011-08-29 11:32:19'
            ],
            [
                'id' => 45,
                'arquivo' => '/media/images/galerias/slide-45.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2011-08-29 11:32:20',
                'updated_at' => '2011-08-29 11:32:20'
            ],
            [
                'id' => 46,
                'arquivo' => '/media/images/galerias/slide-46.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 0,
                'created_at' => '2011-08-29 11:33:07',
                'updated_at' => '2011-08-29 11:33:07'
            ],
            [
                'id' => 47,
                'arquivo' => '/media/images/galerias/slide-47.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 1,
                'created_at' => '2011-08-29 11:33:08',
                'updated_at' => '2011-08-29 11:33:08'
            ],
            [
                'id' => 48,
                'arquivo' => '/media/images/galerias/slide-48.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2011-08-29 11:33:08',
                'updated_at' => '2011-08-29 11:33:08'
            ],
            [
                'id' => 49,
                'arquivo' => '/media/images/galerias/slide-49.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 3,
                'created_at' => '2011-08-29 11:33:09',
                'updated_at' => '2011-08-29 11:33:09'
            ],
            [
                'id' => 50,
                'arquivo' => '/media/images/galerias/slide-50.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 4,
                'created_at' => '2011-08-29 11:33:09',
                'updated_at' => '2011-08-29 11:33:09'
            ],
            [
                'id' => 51,
                'arquivo' => '/media/images/galerias/slide-51.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 5,
                'created_at' => '2011-08-29 11:33:09',
                'updated_at' => '2011-08-29 11:33:09'
            ],
            [
                'id' => 52,
                'arquivo' => '/media/images/galerias/slide-52.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 6,
                'created_at' => '2011-08-29 11:33:10',
                'updated_at' => '2011-08-29 11:33:10'
            ],
            [
                'id' => 53,
                'arquivo' => '/media/images/galerias/slide-53.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 7,
                'created_at' => '2011-08-29 11:33:10',
                'updated_at' => '2011-08-29 11:33:10'
            ],
            [
                'id' => 54,
                'arquivo' => '/media/images/galerias/slide-54.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 8,
                'created_at' => '2011-08-29 11:33:11',
                'updated_at' => '2011-08-29 11:33:11'
            ],
            [
                'id' => 55,
                'arquivo' => '/media/images/galerias/slide-55.jpg',
                'legenda' => 'Imagem de Produto de exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 1,
                'link' => null,
                'ordem' => 9,
                'created_at' => '2011-08-29 11:33:11',
                'updated_at' => '2011-08-29 11:33:11'
            ],
            [
                'id' => 61,
                'arquivo' => '/media/images/galerias/slide-61.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 61,
                'created_at' => '2011-08-29 11:33:29',
                'updated_at' => '2011-08-29 11:33:29'
            ],
            [
                'id' => 62,
                'arquivo' => '/media/images/galerias/slide-62.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 62,
                'created_at' => '2011-08-29 11:33:29',
                'updated_at' => '2011-08-29 11:33:29'
            ],
            [
                'id' => 63,
                'arquivo' => '/media/images/galerias/slide-63.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 63,
                'created_at' => '2011-08-29 11:33:30',
                'updated_at' => '2011-08-29 11:33:30'
            ],
            [
                'id' => 64,
                'arquivo' => '/media/images/galerias/slide-64.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 64,
                'created_at' => '2011-08-29 11:33:30',
                'updated_at' => '2011-08-29 11:33:30'
            ],
            [
                'id' => 65,
                'arquivo' => '/media/images/galerias/slide-65.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 65,
                'created_at' => '2011-08-29 11:33:31',
                'updated_at' => '2011-08-29 11:33:31'
            ],
            [
                'id' => 66,
                'arquivo' => '/media/images/galerias/slide-66.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 66,
                'created_at' => '2011-08-29 11:33:31',
                'updated_at' => '2011-08-29 11:33:31'
            ],
            [
                'id' => 67,
                'arquivo' => '/media/images/galerias/slide-67.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 67,
                'created_at' => '2011-08-29 11:33:32',
                'updated_at' => '2011-08-29 11:33:32'
            ],
            [
                'id' => 68,
                'arquivo' => '/media/images/galerias/slide-68.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 68,
                'created_at' => '2011-08-29 11:33:32',
                'updated_at' => '2011-08-29 11:33:32'
            ],
            [
                'id' => 69,
                'arquivo' => '/media/images/galerias/slide-69.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 69,
                'created_at' => '2011-08-29 11:33:32',
                'updated_at' => '2011-08-29 11:33:32'
            ],
            [
                'id' => 70,
                'arquivo' => '/media/images/galerias/slide-70.jpg',
                'legenda' => 'Imagem de Segundo Produto de Exemplo',
                'slides' => null,
                'galerias' => null,
                'produtos' => 2,
                'link' => null,
                'ordem' => 70,
                'created_at' => '2011-08-29 11:33:33',
                'updated_at' => '2011-08-29 11:33:33'
            ],
            [
                'id' => 76,
                'arquivo' => '/uploads/slide-76.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => null,
                'produtos' => null,
                'link' => null,
                'ordem' => 76,
                'created_at' => '2011-09-07 04:27:24',
                'updated_at' => '2011-09-07 04:27:24'
            ],
            [
                'id' => 77,
                'arquivo' => '/uploads/slide-77.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => null,
                'produtos' => null,
                'link' => null,
                'ordem' => 77,
                'created_at' => '2011-09-07 04:28:18',
                'updated_at' => '2011-09-07 04:28:18'
            ],
            [
                'id' => 78,
                'arquivo' => '/media/images/galerias/slide-78.jpg',
                'legenda' => 'Imagem de Slides Home',
                'slides' => 1,
                'galerias' => null,
                'produtos' => null,
                'link' => 'http://treinamento.marketingdeweb.com/pagina-de-exemplo/',
                'ordem' => 1,
                'created_at' => '2012-03-05 06:15:27',
                'updated_at' => '2012-03-05 06:15:27'
            ],
            [
                'id' => 79,
                'arquivo' => '/media/images/galerias/slide-79.jpg',
                'legenda' => 'Imagem de Slides Home',
                'slides' => 1,
                'galerias' => null,
                'produtos' => null,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2012-03-05 06:15:41',
                'updated_at' => '2012-03-05 06:15:41'
            ],
            [
                'id' => 83,
                'arquivo' => '/media/images/galerias/slide-83.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 4,
                'created_at' => '2012-03-29 06:55:18',
                'updated_at' => '2012-03-29 06:55:18'
            ],
            [
                'id' => 84,
                'arquivo' => '/media/images/galerias/slide-84.jpg',
                'legenda' => 'Imagem de Galeria galeb',
                'slides' => null,
                'galerias' => 3,
                'produtos' => null,
                'link' => null,
                'ordem' => 3,
                'created_at' => '2012-03-29 07:01:44',
                'updated_at' => '2012-03-29 07:01:44'
            ],
            [
                'id' => 85,
                'arquivo' => '/media/images/galerias/slide-85.jpg',
                'legenda' => 'Imagem de Galeria galeb',
                'slides' => null,
                'galerias' => 3,
                'produtos' => null,
                'link' => null,
                'ordem' => 0,
                'created_at' => '2012-03-29 07:01:46',
                'updated_at' => '2012-03-29 07:01:46'
            ],
            [
                'id' => 86,
                'arquivo' => '/media/images/galerias/slide-86.jpg',
                'legenda' => 'Imagem de Galeria galeb',
                'slides' => null,
                'galerias' => 3,
                'produtos' => null,
                'link' => null,
                'ordem' => 1,
                'created_at' => '2012-03-29 07:01:47',
                'updated_at' => '2012-03-29 07:01:47'
            ],
            [
                'id' => 87,
                'arquivo' => '/media/images/galerias/slide-87.jpg',
                'legenda' => 'Imagem de Galeria galeb',
                'slides' => null,
                'galerias' => 3,
                'produtos' => null,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2012-03-29 07:01:48',
                'updated_at' => '2012-03-29 07:01:48'
            ],
            [
                'id' => 89,
                'arquivo' => '/media/images/galerias/slide-89.jpg',
                'legenda' => 'Imagem de Galeria de exemplo',
                'slides' => null,
                'galerias' => 1,
                'produtos' => null,
                'link' => null,
                'ordem' => 1,
                'created_at' => '2012-04-23 10:28:28',
                'updated_at' => '2012-04-23 10:28:28'
            ],
            [
                'id' => 90,
                'arquivo' => '/media/images/galerias/slide-90.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 2,
                'created_at' => '2012-04-26 07:32:53',
                'updated_at' => '2012-04-26 07:32:53'
            ],
            [
                'id' => 91,
                'arquivo' => '/media/images/galerias/slide-91.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 5,
                'created_at' => '2012-04-26 07:32:55',
                'updated_at' => '2012-04-26 07:32:55'
            ],
            [
                'id' => 92,
                'arquivo' => '/media/images/galerias/slide-92.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 4,
                'created_at' => '2012-04-26 07:32:57',
                'updated_at' => '2012-04-26 07:32:57'
            ],
            [
                'id' => 93,
                'arquivo' => '/media/images/galerias/slide-93.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 11,
                'created_at' => '2012-04-26 07:32:59',
                'updated_at' => '2012-04-26 07:32:59'
            ],
            [
                'id' => 94,
                'arquivo' => '/media/images/galerias/slide-94.jpg',
                'legenda' => 'Imagem de Teste asdad asd ',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 3,
                'created_at' => '2012-04-26 07:33:01',
                'updated_at' => '2012-04-26 07:33:01'
            ],
            [
                'id' => 95,
                'arquivo' => '/media/images/galerias/slide-95.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 1,
                'created_at' => '2012-04-26 07:33:03',
                'updated_at' => '2012-04-26 07:33:03'
            ],
            [
                'id' => 96,
                'arquivo' => '/media/images/galerias/slide-96.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 0,
                'created_at' => '2012-04-26 07:33:06',
                'updated_at' => '2012-04-26 07:33:06'
            ],
            [
                'id' => 97,
                'arquivo' => '/media/images/galerias/slide-97.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 8,
                'created_at' => '2012-04-26 07:33:08',
                'updated_at' => '2012-04-26 07:33:08'
            ],
            [
                'id' => 98,
                'arquivo' => '/media/images/galerias/slide-98.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 7,
                'created_at' => '2012-04-26 07:33:10',
                'updated_at' => '2012-04-26 07:33:10'
            ],
            [
                'id' => 99,
                'arquivo' => '/media/images/galerias/slide-99.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 9,
                'created_at' => '2012-04-26 07:33:13',
                'updated_at' => '2012-04-26 07:33:13'
            ],
            
            [
                'id' => 100,
                'arquivo' => '/media/images/galerias/slide-100.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 10,
                'created_at' => '2012-05-08 11:34:49',
                'updated_at' => '2012-05-08 11:34:49'
            ],
            [
                'id' => 101,
                'arquivo' => '/media/images/galerias/slide-101.jpg',
                'legenda' => 'Imagem de Slides Home',
                'slides' => 1,
                'galerias' => null,
                'produtos' => null,
                'link' => null,
                'ordem' => 101,
                'created_at' => '2012-07-04 19:16:39',
                'updated_at' => '2012-07-04 19:16:39'
            ],
            [
                'id' => 102,
                'arquivo' => '/media/images/galerias/slide-102.jpg',
                'legenda' => 'Imagem de Teste',
                'slides' => null,
                'galerias' => 4,
                'produtos' => null,
                'link' => null,
                'ordem' => 6,
                'created_at' => '2012-08-10 15:22:26',
                'updated_at' => '2012-08-10 15:22:26'
            ],
        ]);
    }
}